apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          args:
            - --provider=keycloak
            - --client-id=oauth2-proxy
            - --client-secret=P3E9xeQA50TdTPpt2VopXdx2lIuYzfvxss
            - --redirect-url=https://arena.acadnet.eu/oauth2/callback
            - --email-domain=*
            - --cookie-secret=1VDtVMSe4oVgiPh11A80X08JQ4Et0FCwlGvNaevUr80=
            - --cookie-secure=true
          ports:
            - containerPort: 4180

