apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: monitoring
spec:
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP

