apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['host.docker.internal:9100']

      - job_name: 'cadvisor'
        static_configs:
          - targets: ['host.docker.internal:8080']

      - job_name: 'web-app'
        static_configs:
          - targets: ['host.docker.internal:5000']

      - job_name: 'postgres'
        static_configs:
          - targets: ['host.docker.internal:9187']
