apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['host.minikube.internal:9100']

      - job_name: 'cadvisor'
        static_configs:
          - targets: ['host.minikube.internal:8080']

      - job_name: 'aspnet-metrics'
        metrics_path: /metrics
        static_configs:
          - targets: ['host.minikube.internal:8081']
