version: '3.8'

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    network_mode: host
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    environment:
      - TZ=UTC
    labels:
      - "monitoring=cadvisor"
    extra_hosts:
      - "localhost:0.0.0.0"  # Ensure it binds to IPv4 0.0.0.0

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    environment:
      - TZ=UTC
    labels:
      - "monitoring=node-exporter"
    extra_hosts:
      - "localhost:0.0.0.0"  # Ensure it binds to IPv4 0.0.0.0

