apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth2-secret
  namespace: monitoring
type: Opaque
stringData:
  client-id: kong-gateway
  client-secret: uliF8ms9dbmveuKVtNULpRwX7oGuB5dF
  cookie-secret: 3y2mlT4fL37n28sxCKctK17KO5I+26+8
