apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway-oauth2-proxy
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-gateway-oauth2-proxy
  template:
    metadata:
      labels:
        app: kong-gateway-oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
        args:
          - --provider=oidc
          - --oidc-issuer-url=https://arena.acadnet.eu/monitoring/keycloak/realms/master
          - --client-id=$(OAUTH2_PROXY_CLIENT_ID)
          - --client-secret=$(OAUTH2_PROXY_CLIENT_SECRET)
          - --cookie-secret=$(OAUTH2_PROXY_COOKIE_SECRET)
          - --redirect-url=https://arena.acadnet.eu/monitoring/oauth2/callback
          - --email-domain=*
          - --upstream=http://grafana:3000
          - --http-address=0.0.0.0:4180
          - --skip-provider-button=true
          - --cookie-secure=true
          - --code-challenge-method=S256
          - --proxy-prefix=/monitoring/oauth2
          - --skip-auth-route=/monitoring/oauth2/callback
        env:
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: grafana-oauth2-secret
                key: client-id
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: grafana-oauth2-secret
                key: client-secret
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: grafana-oauth2-secret
                key: cookie-secret
        ports:
        - containerPort: 4180
