apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
  labels:
    name: grafana-config
data:
  grafana.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true

  grafana.ini: |
    [server]
    root_url = %(protocol)s://%(domain)s:%(http_port)s/monitoring/grafana/
    serve_from_sub_path = true
    [auth]
    disable_login_form = true
    disable_signout_menu = true
    [auth.anonymous]
    enabled = true