apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
  labels:
    name: grafana-config
data:
  grafana.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true

  grafana.ini: |
    [auth]
    allow_embedding = true

    [server]
    enable_cors = true
    root_url = %(protocol)s://%(domain)s:%(http_port)s/monitoring/grafana/
    serve_from_sub_path = true
    # [auth]
    # disable_login_form = true
    # disable_signout_menu = true
    # [auth.anonymous]
    # enabled = true

    [auth.generic_oauth]
    enabled = true
    name = Keycloak
    allow_sign_up = true
    client_id = kong-gateway
    client_secret = zObsvDw2nwYrV449TjSaE9fx79L79BlC
    scopes = openid profile email
    auth_url = https://arena.acadnet.eu/monitoring/keycloak/realms/master/protocol/openid-connect/auth
    token_url = https://arena.acadnet.eu/monitoring/keycloak/realms/master/protocol/openid-connect/token
    api_url = https://arena.acadnet.eu/monitoring/keycloak/realms/master/protocol/openid-connect/userinfo
